---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      
      # downloads dependencies
      - run: |
          yarn
          yarn global add typescript

      # tries to save dependencies folder to cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      # build distribution folder
      - run: yarn build

  test:
    docker:
      - image: circleci/node:10

    steps:
      - run: # example

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test
